name: Deploy S3 Static Page
description: 'deploy static to S3'
author: "Dong Keon Kim"
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  aws_key_id:
    description: 'aws key id'
    required: true
  aws_secret_access-key:
    description: 'aws secret access key'
    required: true
  aws_bucket:
    description: 'aws bucket name'
    required: true
  source_dir:
    required: true
    description: 'directory to upload'
outputs:
  object_key:
    description: 'object key'
  object_locations:
    description: 'object locations'
runs:
  using: 'node12'
  main: 'dist/index.js'

